default:
    trainer: ppo
    batch_size: 2024
    beta: 5.0e-3
    buffer_size: 20240
    epsilon: 0.2
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 1.0e6
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    hidden_units: 256
    time_horizon: 1000
    sequence_length: 64
    summary_freq: 5000
    use_recurrent: false
    use_curiosity: false
    use_elo_rating: false
    curiosity_strength: 0.01
    curiosity_enc_size: 128
    gamma: 0.995

FootballLearn:
    max_steps: 10.0e6
    use_elo_rating: true

FootballGhost:
    trainer: ghost
    ghost_master_brain: FootballLearn
    ghost_num_policies: 3
    ghost_recent_ckpts_threshold: 10
    ghost_prob_sample_only_recent: 0.5